
set-option -g base-index 1

unbind r
unbind-key T
bind r source-file ~/.tmux.conf

set -g default-terminal "xterm-256color"
set -as terminal-overrides ",xterm-256color:RGB"
set -s extended-keys on
set -as terminal-features 'xterm-256color:extkeys'

set -g mouse on

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

set-window-option -g mode-keys vi

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set-option -g status-position top

# set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux#v2.1.0'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'nhdaly/tmux-better-mouse-mode'
set -g @plugin 'laktak/extrakto'
set -g @plugin '27medkamal/tmux-session-wizard'

set -g @catppuccin_window_default_text " #W"
set -g @catppuccin_window_current_text " #W"
set -g @catppuccin_window_text " #W"

# Enable automatic window renaming based on the current foreground process
set-option -g allow-rename off 
set-option -g automatic-rename off

set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application} #{E:@catppuccin_status_session}"

set -g set-clipboard on
set -s allow-passthrough on
set -as terminal-features ',xterm-256color:clipboard'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

set -g status-style bg=default
set-option -g @plugin 'b0o/tmux-autoreload'
set -g @session-wizard 's'

